version: '3.8'

services:
  portugal-tax-timetravel:
    build: .
    container_name: portugal-tax-timetravel
    restart: unless-stopped
    networks:
      - home-server_default
    ports:
      - "8089:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.tax-timetravel.rule=Host(`${TAX_TIMETRAVEL_DOMAIN}`)
      - traefik.http.routers.portugal-tax-timetravel.entrypoints=web,websecure
      - traefik.http.routers.portugal-tax-timetravel.tls.certresolver=myresolver
networks:
  home-server_default:
    external: true
